version: "3.9"
services:
  web:
    build:
      context: .
      target: dev
    image: blog
    container_name: blog
    working_dir: /blog
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle
      - yarn_cache:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres:
  bundler_gems:
  yarn_cache:
