default: &default
  adapter: postgresql
  pool: 5
  username: bugledev
  password: bugledev

development:
  <<: *default
  host: postgres
  database: blog_development

test:
  <<: *default
  host: db
  database: blog_test
