meta_product_name: "Ana Nunes da Silva"
meta_title: "Ana Nunes da Silva - thoughts and learnings on software development"
meta_description: "A personal blog on web development mainly focused on ruby and rails"
meta_keywords: "web development, ruby, rails, tdd, rspec, agile, programming, tech"
meta_image: "meta_image.jpg"
twitter_account: "@akbns"
