name: Blog CI

on: push 

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:11
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: rails_blog_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Install dependent libraries
      run: |
        sudo apt-get update && sudo apt-get install -y libvips-dev
          
    - name: Setup Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6

    - name: Ruby Gem cache
      uses: actions/cache@v1
      with:
       path: vendor/bundle
       key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
       restore-keys: |
         ${{ runner.os }}-gems-

    - name: Install ruby dependencies
      run: |
       gem install bundler -v 2.0.2
       bundle config set deployment 'true'
       bundle install --jobs 4 --retry 3
  
    - name: Setup Database
      run: |
        cp .github/config/database.yml config/database.yml
        bundle exec rake db:create
        bundle exec rake db:schema:load

    - name: Run Tests
      run: |
       bundle exec rspec spec

