# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on: push

jobs:
  test:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:11
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6

    - name: Ruby Gem cache
      uses: actions/cache@v1
      with:
       path: vendor/bundle
       key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
       restore-keys: |
         ${{ runner.os }}-gems-

    - name: Install Ruby dependencies
      run: |
       gem install bundler -v 2.0.2
       bundle config set deployment 'true'
       bundle install --jobs 4 --retry 3
       bundle exec rake db:create
       bundle exec rake db:schema:load

    - name: Install libvips
      run: |
        sudo apt-get update && sudo apt-get install -y libvips-dev
